config/routes.rb
Rails.application.routes.draw do
  resources :users, :projects, :expenses, :prints

  resources :events do
    member do
      get 'submit'
    end
    member do
      get 'reject'
    end
  end

  get 'timesheet' => 'events#timesheet', as: :timesheet
  get 'expense_report' => 'expenses#expense_report', as: :expense_report

	namespace :admin do
		resources :clients
end

	resources :clients do
	    get "delete"
	end

	resources :projects do
	    get "delete"
	end


	get 'admin' => 'admin#dashboard', as: :admin
  get 'dashboard' => 'users#dashboard', as: :dashboard


	get 'sign_in' => 'sessions#new', as: :sign_in
	post 'sign_in' => 'sessions#create'
	delete 'sign_in' => 'sessions#delete', as: :end_session
	get 'sign_out' => 'sessions#delete', as: :sign_out

	root 'welcome#calendar'
end

app/views/admin/_client_index.html.erb
<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= link_to "Edit", edit_admin_client_path(client), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Show", client_path(client), class: "btn btn-default" %></td>

  </tr>
<% end %>

app/views/admin/_project_index.html.erb
<% @projects.each do |project| %>
  <tr>
    <td><%= project.number%> | <%= project.name %></td>
    <td><%= link_to "Edit", edit_project_path(project), remote: true, class: "btn btn-default" %></td>
  </tr>
<% end %>

app/views/admin/_user_index.html.erb
<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.role %></td>
    <td><%= link_to "Edit", edit_user_path(user), remote: true, class: "btn btn-default" %></td>
  </tr>
<% end %>

app/views/admin/dashboard.html.erb
<div class="row">
  <div class="col col-md-4">
    <h1>Clients</h1>
    <%= link_to "Add Client", new_admin_client_path(@client), remote: true, class: "btn" %>
    <div id="client-modal" class="modal fade"></div>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render 'client_index' %>
      </tbody>
    </table>
  </div>

  <div class="col col-md-4 ">
    <h1>Projects</h1>
    <%= link_to "Add Project", new_project_path(@project), remote: true, class: "btn" %>
    <div class="new-project"></div>
    <table class="table">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render 'project_index' %>
        </tbody>
      </table>
    <div id="project-modal", class="modal fade"></div>
  </div>
  <div class="col col-md-4 ">
    <div class="employee">
      <h1>Employees</h1>
      <%= link_to "Add Employee", new_user_path(@employee), remote: true, class: "btn" %>
      <div class="new-user"></div>
      <table class="table">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render 'user_index' %>
          </tbody>
        </table>
      <div id="user-modal", class="modal fade"></div>
    </div>
    <div class="billables">
      <h2>Timesheets</h2><hr>
      <h2>Expenses </h2><hr>

    </div>

  </div>
</div>


</div>