config/routes.rb
Rails.application.routes.draw do
  resources :users, :projects, :expenses, :prints

  resources :events do
    member do
      get 'submit'
    end
    member do
      get 'reject'
    end
  end

  get 'timesheet' => 'events#timesheet', as: :timesheet
  get 'expense_report' => 'expenses#expense_report', as: :expense_report

	namespace :admin do
		resources :clients
end

	resources :clients do
	    get "delete"
	end

	resources :projects do
	    get "delete"
	end


	get 'admin' => 'admin#dashboard', as: :admin
  get 'dashboard' => 'users#dashboard', as: :dashboard


	get 'sign_in' => 'sessions#new', as: :sign_in
	post 'sign_in' => 'sessions#create'
	delete 'sign_in' => 'sessions#delete', as: :end_session
	get 'sign_out' => 'sessions#delete', as: :sign_out

	root 'welcome#calendar'
end

app/models/client.rb
class Client < ApplicationRecord
	 has_many :projects
	 has_many :events, through: :projects
	 has_many :expenses, through: :projects
	 has_many :prints, through: :projects
	 validates :name, presence: true
	 scope :sorted, -> { order(name: "ASC") }

end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  def index
    @clients = Client.all.sorted
    ## keep query in controller, not view
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @clients = Client.all.to_a
    @client = Client.create(client_params)
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @clients = Client.all.to_a
    @client = Client.find(params[:id])

    @client.update_attributes(client_params)
  end

  def delete
    @client = Client.find(params[:client_id])
  end

  def destroy
    @clients = Client.all.to_a
    @client = Client.find(params[:id])
    @client.destroy
  end

  private

  def client_params
    params.require(:client).permit(:first_name, :last_name, :name)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :sign_in


  def index
    @clients = Client.all.to_a.sorted
    ## keep query in controller, not view
  end

  def show
    @client = Client.find(params[:id])
    @events = @client.events.all
    @prints = @client.prints.all
    @expenses = @client.expenses.not_nil
  end


  def client_expense()
    @client = Client.find(params[:id])
    total =[]
    @client.expenses.each do |e|
      total << e.amount
    end
    @total = total.sum


    respond_to do |format|
        format.pdf do
          render pdf: "client_expense"   # Excluding ".pdf" extension.
        end
      end

  end

  def new
    @client = Client.new
  end

  def create
    @clients = Client.all.to_a
    @client = Client.create(client_params)
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @clients = Client.all.to_a
    @client = Client.find(params[:id])

    @client.update_attributes(client_params)
  end

  def delete
    @client = Client.find(params[:client_id])
  end

  def destroy
    @clients = Client.all.to_a
    @client = Client.find(params[:id])
    @client.destroy
  end

private
  def client_params
    params.require(:client).permit(:first_name, :last_name, :name, :billing_contact, :billing_company, :billing_address1, :billing_address2, :billing_phone, :billing_city, :billing_state, :billing_zip)
  end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/views/clients/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Client</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Client", client_path(@client), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/clients/_edit.html.erb
<%= render "form" %>

app/views/clients/_index.html.erb
<% @clients.each do |client| %>
  <tr>
    <td><%= client.first_name %></td>
    <td><%= client.last_name %></td>
    <td><%= link_to "Edit", edit_client_path(client), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", client_delete_path(client), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/clients/_new.html.erb
<%= render "form" %>

app/views/clients/_save.js.erb
$("ul.errors").html("")
<% if @client.errors.any? %>
  <% @client.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".client-index").html("<%= escape_javascript(render 'index') %>")
  $("#client-modal").modal("hide")
<% end %>

app/views/clients/client_expense.pdf.erb
<body>
  <h1> Festina Lente | Swift Solutions</h1>
  <hr>
  <h3> Expenses for <%=@client.name%></h3>


<table  class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>Project</th>
      <th>Vendor </th>
      <th>Description </th>
      <th>Cost</th>
      <th>Mileage </th>
    </tr>
  </thead>
  <tbody class="project-index">
    <% @client.expenses.each do |expense|%>
      <tr>
        <td> <%= expense.project.number %></td>
        <td> <%= expense.project.name %></td>
        <td> <%= expense.vendor %></td>
        <td> <%= expense.description %></td>
        <td> $<%= expense.amount || "N/A"%></td>
        <td> <%= expense.mileage  || "N/A" %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<h4> Total: $ <%= @total %> </br></h4>


<p> Created at: <%= DateTime.now %></p>

app/views/clients/create.js.erb
<%= render "save" %>

app/views/clients/delete.js.erb
$("#client-modal").html("<%= escape_javascript(render 'delete') %>")
$("#client-modal").modal("show")

app/views/clients/destroy.js.erb
<%= render "save" %>

app/views/clients/edit.js.erb
$("#client-modal").html("<%= escape_javascript(render 'edit') %>")
$("#client-modal").modal("show")

app/views/clients/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New Client", new_client_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-client"></div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>First</th>
        <th>Last</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="client-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="client-modal" class="modal fade"></div>

app/views/clients/new.js.erb
$("#client-modal").html("<%= escape_javascript(render 'new') %>")
$("#client-modal").modal("show")

app/views/clients/show.html.erb
<h1><%= @client.name%> | <%= @client.first_name %> <%= @client.last_name%></h1>
<hr>


<div class="row">
  <% @client.projects.each do |p| %>
  <div class="col col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"> <h3 class="panel-title"><%= p.name%></h3> </div>
      <div class="panel-body">
        <h5>Project No. <%= p.number %></h5>
        <%if p.address1%><h5><%= p.address1 %></h5><%end%>
        <%if p.address2%><h5><%= p.address2 %></h5><%end%>
        <%if p.city%><h5><%= p.city %></h5><%end%>
        <%if p.zip%><h5><%= p.zip %></h5><%end%>
        <%if p.description%><h5><%= p.description %></h5><%end%>
        <%if p.square_footage%><h5>Square Footage: <%= p.square_footage %></h5><%end%>
        <%if p.status%><h5>Status: <%= p.status %></h5><%end%>
        <%= link_to "Add or Update Project Details", edit_project_path(p), remote:true, class:'btn btn-outline btn-info' %>
        <div id='project-modal' class="modal modal-fade"></div>

        </div>
    </div>
  </div>
  <% end %>

  <div class="col col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"> <h3 class="panel-title">Billing Details</h3></div>
      <div class="panel-body">
          <%= @client.billing_contact%>
          <h5><%= @client.billing_company %></h5>
          <h5><%= @client.billing_address1 %></h5>
          <h5><%= @client.billing_address2 %></h5>
          <h5><%= @client.billing_city %>, <%= @client.billing_state %> <%= @client.billing_zip %></h5>
          <%= link_to "Add or Update Billing Details", edit_client_path(@client), remote:true, class:'btn btn-outline btn-info' %>

      </div>
      </div>
    </div>
    <%if @client.expenses.count >= 1%>
    <div class="col col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading"> <h3 class="panel-title">Expenses</h3></div>
        <div class="panel-body">

          <table  class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>No.</th>
                <th>Project</th>
                <th>Vendor </th>
                <th>Description </th>
                <th>Cost</th>
              </tr>
            </thead>
            <tbody class="project-index">
              <% @client.expenses.each do |expense|%>
                <tr>
                  <td> <%= expense.project.number %></td>
                  <td> <%= expense.project.name %></td>
                  <td> <%= expense.vendor %></td>
                  <td> <%= expense.description %></td>
                  <td> $<%= expense.amount %></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
        </div>
      </div>
    </div>
    <%end%>
  </div>


<div id='client-modal' class="modal modal-fade"></div>

app/views/clients/update.js.erb
<%= render "save" %>