config/routes.rb
Rails.application.routes.draw do
  resources :users, :projects, :expenses, :prints

  resources :events do
    member do
      get 'submit'
    end
    member do
      get 'reject'
    end
  end

  get 'timesheet' => 'events#timesheet', as: :timesheet
  get 'expense_report' => 'expenses#expense_report', as: :expense_report

	namespace :admin do
		resources :clients
end

	resources :clients do
	    get "delete"
	end

	resources :projects do
	    get "delete"
	end


	get 'admin' => 'admin#dashboard', as: :admin
  get 'dashboard' => 'users#dashboard', as: :dashboard


	get 'sign_in' => 'sessions#new', as: :sign_in
	post 'sign_in' => 'sessions#create'
	delete 'sign_in' => 'sessions#delete', as: :end_session
	get 'sign_out' => 'sessions#delete', as: :sign_out

	root 'welcome#calendar'
end

app/models/project.rb
class Project < ApplicationRecord
	 belongs_to :client
	 has_many :events
	 has_many :users, through: :events
	 has_many :expenses
	 has_many :prints
	 validates :client, presence: true
	 validates :number, presence: true

	 scope :sorted, -> { order(number: "ASC") }
         scope :active, -> {where.not(status: "Archived")}
            # this simply makes active default behavior, belt + suspenders :) 
        STATUS = [
            'Archived',
            'Active'].freeze
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :sign_in
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_projects


  def index
      @projects = Project.active.sorted.to_a
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      flash[:notice]="Project Added"
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @project.update_attributes(project_params)
    if @project.save
        flash[:notice]="Project Updated"
    else
        render 'edit'
    end
  end

  def delete
  end

  def destroy
    @project.destroy
  end

private

  def project_params
    params.require(:project).permit(:client_id, :name, :address1, :address2, :city, :state, :zip, :state, :square_footage, :status, :description, :number)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_projects
      @projects = Project.active.sorted.to_a
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/projects/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Project</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Project", project_path(@project), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/projects/_edit.html.erb
<%= render "form" %>

app/views/projects/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for @project, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
        <h4>Project Information </h4><hr>

        <%= f.input :name %>
       <div class="form-group">
          <%= f.label :client %>
          <%= f.collection_select :client_id, Client.all, :id, :last_name %>
       </div>
       <%= f.input :number %>
       <div class="form-group">
            <%= f.label :status, required: true %>
            <%= f.collection_select :status, Project::STATUS, :to_s, :to_s, :include_blank => false %>
       </div>
       <%= f.input :description %>
       <%= f.input :status %>
       <%= f.input :square_footage %>
       <%= f.input :address1 %>
       <%= f.input :address2 %>
       <%= f.input :city %>
       <%= f.input :zip %>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_index.html.erb
<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.client.last_name %></td>
    <td><%= project.number%></td>
    <td><%= link_to "Edit", edit_project_path(project), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", project_delete_path(project), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/projects/_new.html.erb
<%= render "form" %>

app/views/projects/_save.js.erb
$("ul.errors").html("")
<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".project-index").html("<%= escape_javascript(render 'index') %>")
  $("#project-modal").modal("hide")
<% end %>

app/views/projects/create.js.erb
<%= render "save" %>

app/views/projects/delete.js.erb
$("#project-modal").html("<%= escape_javascript(render 'delete') %>")
$("#project-modal").modal("show")

app/views/projects/destroy.js.erb
<%= render "save" %>

app/views/projects/edit.js.erb
$("#project-modal").html("<%= escape_javascript(render 'edit') %>")
$("#project-modal").modal("show")

app/views/projects/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to "New Project", new_project_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-project"></div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Project</th>
        <th>Client</th>
        <th>Number</th>
        <td>Edit</td>
        <td>Delete</td>
      </tr>
    </thead>
    <tbody class="project-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="project-modal" class="modal fade"></div>

app/views/projects/new.js.erb
$("#project-modal").html("<%= escape_javascript(render 'new') %>")
$("#project-modal").modal("show")

app/views/projects/show.html.erb
<h1>Project Details</h1>

app/views/projects/update.js.erb
<%= render "save" %>