config/routes.rb
Rails.application.routes.draw do
  resources :users, :projects, :expenses, :prints

  resources :events do
    member do
      get 'submit'
    end
    member do
      get 'reject'
    end
  end

  get 'timesheet' => 'events#timesheet', as: :timesheet
  get 'expense_report' => 'expenses#expense_report', as: :expense_report

	namespace :admin do
		resources :clients
end

	resources :clients do
	    get "delete"
	end

	resources :projects do
	    get "delete"
	end


	get 'admin' => 'admin#dashboard', as: :admin
  get 'dashboard' => 'users#dashboard', as: :dashboard


	get 'sign_in' => 'sessions#new', as: :sign_in
	post 'sign_in' => 'sessions#create'
	delete 'sign_in' => 'sessions#delete', as: :end_session
	get 'sign_out' => 'sessions#delete', as: :sign_out

	root 'welcome#calendar'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modals.html.erb
<div id="expense-modal" class="modal fade"></div>
<div id="print-modal" class="modal fade"></div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"> Festina Lente | Swift Solutions </a>
   </div>
   <ul class="nav navbar-nav navbar-right">
     <% if @current_user %>
            <% if @current_user.role =='Admin'%>
            <li><%= link_to 'Admin Dashboard', admin_path %></li>
            <%end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Log <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Time Entries', root_path %></li>
            <li><%= link_to 'Expense', new_expense_path, remote:true %></li>
            <li><%= link_to 'Prints', new_print_path, remote:true %></li>
          </ul>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">View <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Time Entries', events_path %></li>
              <li><%= link_to 'Expenses', expenses_path %></li>
              <li><%= link_to 'Prints', prints_path %></li>
            </ul>
          <% end %>
          <%if @current_user%>
         <li><%= link_to 'Hello, ' + @current_user.username.upcase, root_path %></li>
         <li><%= link_to 'Sign Out', sign_out_path%></li>
         <%end%>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Festina Lente" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Festina Lente" %>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class='container'>
        <%= render 'layouts/modals'%>
        <%= render 'layouts/messages' %>
        <%= yield %>
        <div id='remote_container'></div>
      </div>
    </main>
  </body>
</html>